FIRST = {
    "PROGRAM": {"FOR", "IDENTIFIER", "LEFT_BRACE"},
    "STMT_LIST": {"FOR", "IDENTIFIER", "LEFT_BRACE", "ε"},
    "STMT": {"FOR", "IDENTIFIER", "LEFT_BRACE"},
    "FOR_LOOP": {"FOR"},
    "INIT": {"IDENTIFIER"},                     
    "ASSIGN_EXPR": {"IDENTIFIER"},              # needed to parse INIT correctly
    "COND": {"IDENTIFIER", "NUMBER", "LEFT_PAREN", "ε"},
    "UPDATE": {"IDENTIFIER", "INCREMENT", "DECREMENT", "ε"},
    "ASSIGN_STMT": {"IDENTIFIER"},
    "INCREMENT": {"IDENTIFIER"},
    "DECREMENT": {"IDENTIFIER"},
    "BLOCK": {"LEFT_BRACE"},
    "EXPR": {"IDENTIFIER", "NUMBER", "LEFT_PAREN"},
    "EXPR_PRIME": {"PLUS", "MINUS", "ε"},
    "TERM": {"IDENTIFIER", "NUMBER", "LEFT_PAREN"},
    "TERM_PRIME": {"MULTIPLY", "DIVIDE", "ε"},
    "ADD_OP": {"PLUS", "MINUS"},
    "MUL_OP": {"MULTIPLY", "DIVIDE"},
    "FACTOR": {"IDENTIFIER", "NUMBER", "LEFT_PAREN"},
    "REL_OP": {"LESS_THAN", "GREATER_THAN", "LESS_EQUAL", "GREATER_EQUAL", "EQUALS", "NOT_EQUAL"}
}

FOLLOW = {
    "PROGRAM": {"$"},
    "STMT_LIST": {"RIGHT_BRACE", "$"},
    "STMT": {"FOR", "IDENTIFIER", "LEFT_BRACE", "RIGHT_BRACE", "$"},
    "FOR_LOOP": {"FOR", "IDENTIFIER", "LEFT_BRACE", "RIGHT_BRACE", "$"},
    "INIT": {"SEMICOLON"},
    "ASSIGN_EXPR": {"SEMICOLON"},               # after INIT
    "COND": {"SEMICOLON"},
    "UPDATE": {"RIGHT_PAREN"},
    "EXPR": {"SEMICOLON", "RIGHT_PAREN", "LESS_THAN", "GREATER_THAN",
             "LESS_EQUAL", "GREATER_EQUAL", "EQUALS", "NOT_EQUAL"},
    "EXPR_PRIME": {"SEMICOLON", "RIGHT_PAREN", "LESS_THAN", "GREATER_THAN",
                   "LESS_EQUAL", "GREATER_EQUAL", "EQUALS", "NOT_EQUAL"},
    "TERM": {"PLUS", "MINUS", "SEMICOLON", "RIGHT_PAREN", "LESS_THAN", "GREATER_THAN",
             "LESS_EQUAL", "GREATER_EQUAL", "EQUALS", "NOT_EQUAL"},
    "TERM_PRIME": {"PLUS", "MINUS", "SEMICOLON", "RIGHT_PAREN", "LESS_THAN", "GREATER_THAN",
                   "LESS_EQUAL", "GREATER_EQUAL", "EQUALS", "NOT_EQUAL"},
    "FACTOR": {"MULTIPLY", "DIVIDE", "PLUS", "MINUS", "SEMICOLON", "RIGHT_PAREN",
               "LESS_THAN", "GREATER_THAN", "LESS_EQUAL", "GREATER_EQUAL", "EQUALS", "NOT_EQUAL"},
    "REL_OP": {"IDENTIFIER", "NUMBER", "LEFT_PAREN"}
}
